<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7v6dxk3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7v6dxk3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7v6dxk3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7v6dxk3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container7v6dxk3\appDevDebugProjectContainer(array(
    'container.build_hash' => '7v6dxk3',
    'container.build_id' => 'ca1c2fbf',
    'container.build_time' => 1526044870,
), __DIR__.\DIRECTORY_SEPARATOR.'Container7v6dxk3');
