<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB6nafrq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB6nafrq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerB6nafrq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerB6nafrq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerB6nafrq\appDevDebugProjectContainer(array(
    'container.build_hash' => 'B6nafrq',
    'container.build_id' => 'd74fa914',
    'container.build_time' => 1526585512,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerB6nafrq');
