<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9vrn8oc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9vrn8oc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9vrn8oc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9vrn8oc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9vrn8oc\appDevDebugProjectContainer(array(
    'container.build_hash' => '9vrn8oc',
    'container.build_id' => '4e5e6ac8',
    'container.build_time' => 1526286516,
), __DIR__.\DIRECTORY_SEPARATOR.'Container9vrn8oc');
